### PR TITLE
page.py

### PR DESCRIPTION
**Pull request by MosheBrizel**
add the page to add a book

### CODE REVIEW

**Review by NoamAnisfeld — CHANGES_REQUESTED** [review]
Thank you!

A few things to fix before we can merge it:
* No need for a `POST` method on the main route
* Please add an endpoint to see current books in the DB so that we can make sure the adding function actually works
* No reason to use `print` on a web server. If you need a log use the `logging` object
* Use `<label>` for the text next to input fields
* Use `<input type="number">` for numerical input fields

As a side note, it looks like you used `git push --force`. Be careful with it because it might break things.

**Comment by MosheBrizel** [comment]
i change it

**Review by NoamAnisfeld — CHANGES_REQUESTED** [review]
Thanks!

I still don't see an endpoint to show the books on the DB. Without it we can't test the adding function and make sure it actually works.

**Comment by MosheBrizel** [comment]
i finish it @NoamAnisfeld

**Review by NoamAnisfeld — APPROVED** [review]

**Pull request merged**
